version: "3.8"

configs:
  emqx_conf:
    file: ./emqx.conf

services:
  emqx1:
    image: emqx/emqx:latest
    container_name: emqx1
    configs:
      - source: emqx_conf
        target: /opt/emqx/etc/emqx.conf
        mode: 444
    ports: 
      - 31883:1883
      - 38083:18083
    environment:
    - "EMQX_ALLOW__ANONYMOUS=true"
    - "EMQX_NODE_NAME=emqx@node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io, emqx@node4.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.io

  emqx2:
    image: emqx/emqx:latest
    container_name: emqx2
    configs:
      - source: emqx_conf
        target: /opt/emqx/etc/emqx.conf
        mode: 444
    environment:
    - "EMQX_ALLOW__ANONYMOUS=true"
    - "EMQX_NODE_NAME=emqx@node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io, emqx@node4.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node2.emqx.io

  emqx3:
    image: emqx/emqx:latest
    container_name: emqx3
    configs:
      - source: emqx_conf
        target: /opt/emqx/etc/emqx.conf
        mode: 444
    environment:
    - "EMQX_ALLOW__ANONYMOUS=true"
    - "EMQX_NODE_NAME=emqx@node3.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io, emqx@node4.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node3.emqx.io

  emqx4:
    image: emqx/emqx:latest
    container_name: emqx4
    configs:
      - source: emqx_conf
        target: /opt/emqx/etc/emqx.conf
        mode: 444
    environment:
    - "EMQX_ALLOW__ANONYMOUS=true"
    - "EMQX_NODE_NAME=emqx@node4.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io, emqx@node3.emqx.io, emqx@node4.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node4.emqx.io

networks:
  emqx-bridge:
    driver: bridge
