apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-node-red
  labels:
    name: node-red-storage
spec:
  storageClassName: local-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
     path: /path/to/node-red
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-node-red
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      name: node-red-storage
