esphome:
  name: esp8266

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "OTA-PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp8266 Fallback Hotspot"
    password: "FALLBACK-PASSWORD"

captive_portal:

i2c:
  - id: bus_a
    sda: 4
    scl: 5
    scan: True

sensor:
  - platform: sht3xd
    i2c_id: bus_a
    address: 0x45
    update_interval: 60s
    temperature:
      name: "Temperature"
      filters:
        - offset: -5.0
    humidity:
      name: "Humidity"
  - platform: bh1750
    i2c_id: bus_a
    address: 0x23
    update_interval: 60s
    name: "Illuminance"
  - platform: sgp30
    eco2:
      name: "eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "TVOC"
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 60s
